# Dependencies
markdown:             kramdown
highlighter:          rouge


# Gems
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag


# Settings
exclude:              [CNAME, README.md, NOTES.md, LICENSE.md, .gitignore, package.json, bower.json, _js, _scss, _images, gulpfile.js, gulpconfig.js, node_modules, bower_components, gemfile, Gemfile.lock]
permalink:            /:title/
compress_html:
  clippings: all
  comments: all


# Site meta
title:                'Change'
tagline:              'Embrace change.'
description:          'Change is a minimalist Jekyll theme <a href="https://madebyconnor.co/" target="_blank" rel="noopener noreferrer">Made by Connor</a>.'
keywords:             'connor, baer, bear, designer, developer, traveller, design, code, jekyll, change, theme, for hire'
url:                  https://danielamieva.github.io
baseurl:              /change
assets:               /assets
images:               /images/
image:                index-large.jpg
logo:                 /assets/icons/apple-icon-144x144.png
dark_theme:           true

author:
  name:               Daniel Amieva
  bio:                Hi, I'm Daniel, the author of this blog. Nice to meet you!
  image:              author
  url:                https://danielamieva.github.io
  email:              daniel@amieva.in
  twitter:            daniel_amieva

social:
  twitter:            https://twitter.com/daniel_amieva
  instagram:          https://instagram.com/daniel_amieva
  github:             https://github.com/danielamieva
  medium:             https://

version:              3.1.3

github:
  repo:               https://


# Integrations
# typekit:              fcv7rfe

google_fonts:
  Overpass:           400, 600, 800

google_analytics_key:
# google_site_verification:


# Content
excerpt_separator: <!-- Read more -->

navigation:
  GitHub: 
